# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

env:
  JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JRELEASER_NEXUS2_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  JRELEASER_NEXUS2_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

on:
  push:
    branches:
      - master
      - dev
      - feature/*
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating tags and pushing version bumps
      packages: write  # Required for publishing to GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle (8.13)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Setup JReleaser
        uses: jreleaser/release-action@v2
        with:
            version: '1.17.0'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish Package
        run: jreleaser full-release
